version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www/project:delegated
      - ./Docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: "Docker/php/8.1"
      target: app_php_dev
    container_name: "php-sf6-todo"
    volumes:
      - ./Docker/php/8.1/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/project:delegated
    extra_hosts:
      - host.docker.internal:host-gateway
